Controllers/HomeController.cs
using Assignment3_MVC_HospitalRecords.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment3_MVC_HospitalRecords.Controllers
{
    public class HomeController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserTbl user)
        {
            if (ModelState.IsValid)
            {
                using (HospitalRecordsDBContext db = new HospitalRecordsDBContext())
                {
                    var obj = db.UserTbls.Where(a => a.username_.Equals(user.username_) && a.password.Equals(user.password)).FirstOrDefault();
                    if (obj != null)
                    {
                        if (Convert.ToBoolean(obj.admin))
                        {
                            Session["IsAdmin"] = obj.admin.ToString();
                            return RedirectToAction("Admin");
                        }
                        else
                        {
                            Session["IsAdmin"] = obj.admin.ToString();
                            return RedirectToAction("Users");
                        }
                    }
                }
            }
            return View(user);
        }

        public ActionResult Admin()
        {
            if (Session["IsAdmin"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        public ActionResult Users()
        {
            if (Session["IsAdmin"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult Logout()
        {
            return RedirectToAction("Login");
        }
    }
}

Controllers/PatientTblsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment3_MVC_HospitalRecords.Models;

namespace Assignment3_MVC_HospitalRecords.Controllers
{
    public class PatientTblsController : Controller
    {
        private HospitalRecordsDBContext db = new HospitalRecordsDBContext();

        // GET: PatientTbls
        public PartialViewResult All()
        {
            //var patientTbls = db.PatientTbls.Include(p => p.DoctorTbl);
            return PartialView("_Patient",db.PatientTbls.ToList());
        }

        public PartialViewResult AllPat()
        {
            return PartialView("_ViewPatient", db.PatientTbls.ToList());
        }
        // GET: PatientTbls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientTbl patientTbl = db.PatientTbls.Find(id);
            if (patientTbl == null)
            {
                return HttpNotFound();
            }
            return View(patientTbl);
        }

        // GET: PatientTbls/Create
        public ActionResult Create()
        {
            ViewBag.docid = new SelectList(db.DoctorTbls, "Id", "firstname");
            return View();
        }

        // POST: PatientTbls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(String firstname, String lastname)
        {

            PatientTbl patientTbl = new PatientTbl();
            patientTbl.firstname = firstname;
            patientTbl.lastname = lastname;
            patientTbl.admission = DateTime.Now.Date;
            patientTbl.isdischarge = "N";
                db.PatientTbls.Add(patientTbl);
                db.SaveChanges();
                return RedirectToAction("Admin", "Home");
            

   
            return View(patientTbl);
        }

        // GET: PatientTbls/Edit/5
        public ActionResult List()
        {

            /* PatientTbl patientTbl = db.PatientTbls.Find(id);
             ViewBag.docid = new SelectList(db.DoctorTbls, "Id", "firstname", patientTbl.docid);
             return View(patientTbl);*/

            //list
            List<PatientTbl> patientTbl = db.PatientTbls.ToList();
            return View(patientTbl);
        }

        // GET: PatientTbls/Edit/5
        public ActionResult Edit(int? id)
        {

             PatientTbl patientTbl = db.PatientTbls.Find(id);
             ViewBag.docid = new SelectList(db.DoctorTbls, "Id", "firstname", patientTbl.docid);
             return View(patientTbl);

            //list
            //List <PatientTbl> patientTbl = db.PatientTbls.ToList();
            //return View(patientTbl);
        }

        // POST: PatientTbls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,firstname,lastname,docid,admission,discharge,isdischarge")] PatientTbl patientTbl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patientTbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
          //  ViewBag.docid = new SelectList(db.DoctorTbls, "Id", "firstname", patientTbl.docid);
            return View(patientTbl);
        }

        // GET: PatientTbls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientTbl patientTbl = db.PatientTbls.Find(id);
            if (patientTbl == null)
            {
                return HttpNotFound();
            }
            return View(patientTbl);
        }

        // POST: PatientTbls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PatientTbl patientTbl = db.PatientTbls.Find(id);
            db.PatientTbls.Remove(patientTbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult Index(string Searchby, string search)
        {
            if (Searchby == "FirstName")
            {
                return View(db.PatientTbls.Where(x => x.firstname.Contains(search)|| search == null).ToString());

            }
            else
            {
                return View(db.PatientTbls.Where(x => x.lastname.Contains(search) || search == null).ToString());

            }
        }
        /* public ActionResult Search(String input, String )
         {

             PatientTbl patientTbl = db.PatientTbls.Find(id);
             db.PatientTbls.Remove(patientTbl);
             db.SaveChanges();
             return RedirectToAction("Index");
         }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/Admin.cshtml

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript" language="javascript">
    function ClearResults() {
        $("#divDisplay").empty();
    }
</script>

<h2>Welcome Admin</h2>

<table class="auto-style1" border="1">
    <tr style="text-align:center">
        <td>
            @Html.ActionLink("Logout", "Logout", "Home")
        </td>
        <td>
            @Ajax.ActionLink("View Patients", "AllPat", "PatientTbls", new AjaxOptions
       {
           HttpMethod = "GET",
           UpdateTargetId = "divDisplay",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "divLoading",
           OnBegin = "ClearResults"
       })
        </td>
        <td>
            @Ajax.ActionLink("View Patients History", "All", "PatientTbls", new AjaxOptions
       {
           HttpMethod = "GET",
           UpdateTargetId = "divDisplay",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "divLoading",
           OnBegin = "ClearResults"
       })
        <td>
            @Ajax.ActionLink("Edit Patients", "List","PatientTbls", new AjaxOptions
       {
           HttpMethod = "GET",
           UpdateTargetId = "divDisplay",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "divLoading",
           OnBegin = "ClearResults"
       })
        </td>
        <td>
            @Ajax.ActionLink("Edit Doctors", "EditDoctors", new AjaxOptions
       {
           HttpMethod = "GET",
           UpdateTargetId = "divDisplay",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "divLoading",
           OnBegin = "ClearResults"
       })
        </td>
    </tr>
</table>

<div id="divLoading" style="display:none">
    <img src="~/Images/spiffygif_30x30.gif" />
</div>

<div id="divDisplay">

</div>


Views/Home/Login.cshtml
@model Assignment3_MVC_HospitalRecords.Models.UserTbl

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    <fieldset>
        <legend>Login</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <table>
            <tr>
                <td>
                    Username:
                </td>
                <td>
                    @Html.TextBoxFor(a => a.username_)
                </td>
                <td>
                    @Html.ValidationMessageFor(a => a.username_)
                </td>
            </tr>
            <tr>
                <td>
                    Password:
                </td>
                <td>
                    @Html.PasswordFor(a => a.password)
                </td>
                <td>
                    @Html.ValidationMessageFor(a => a.password)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Login" />
                </td>
                <td></td>
            </tr>
        </table>
    </fieldset>
}

Views/Home/Users.cshtml

@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript" language="javascript">
    function ClearResults() {
        $("#divDisplay").empty();
    }
</script>

<h2>Welcome User</h2>

<table class="auto-style1" border="1">
    <tr style="text-align:center">
        <td>
            @Html.ActionLink("Logout", "Logout", "Home")
        </td>
        <td>
            @Ajax.ActionLink("View Patients", "AllPat", "PatientTbls", new AjaxOptions
       {
           HttpMethod = "GET",
           UpdateTargetId = "divDisplay",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "divLoading",
           OnBegin = "ClearResults"
       })
        </td>
        <td>
            @Ajax.ActionLink("View Patients History","All", "PatientTbls", new AjaxOptions
       {
           HttpMethod = "GET",
           UpdateTargetId = "divDisplay",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "divLoading",
           OnBegin = "ClearResults"
       })
        </td>
    </tr>
</table>

<div id="divLoading" style="display:none">
    <img src="~/Images/spiffygif_30x30.gif" />
</div>

<div id="divDisplay" style="margin:auto" >

</div>